### ISSUE TITLE
Add transactions export to csv. 

### ISSUE THREAD

**Issue by odedgoro** [arqma/arqma-electron-wallet#2]
Please add transactions export to csv.

**Comment by odedgoro** [comment]
Any ETA for this feature? I really need it for IRS report.

**Comment by ArqTras** [comment]
That option is available on 
https://github.com/arqma/arqma-gui

**Comment by ArqTras** [comment]
That option is available 
https://github.com/arqma/arqma-gui
We can consider add it too

**Comment by odedgoro** [comment]
Arqma GUI doesn't have Arqma 5.1 update

**Comment by ArqTras** [comment]
It will work till

v13 Date and time (GMT): Thursday, 22 August 2019 22:08:00 block 248200

**Comment by ArqTras** [comment]
Incoming release 2.0.2 include export to csv

**Comment by odedgoro** [comment]
Great. Thanks !!!

**Comment by ArqTras** [comment]
available in release 2.0.2
