### ISSUE TITLE
Artifacts for macOS build not created

### ISSUE THREAD

**Issue by fraimondo** [arqma/arqma-electron-wallet#62]
The GitHub action has an error and the artifacts are not built despite a successful action:

```
Error: /Users/runner/work/arqma-electron-wallet/arqma-electron-wallet not a file
339
 app:electron ⚠️  [FAIL] electron-builder could not build +1ms
```

**Comment by ArqTras** [comment]
The reason for that is missed part related to apple dev account.
Basically I dont have mac box and selfsigned apps made more problems.
If you wanna I can help with build for your own on your mac box

**Comment by marko-lorentz** [comment]
@fraimondo Is still an open issue for you?
