### ISSUE TITLE
Compiling for ARM (raspberry pi 4B)

### ISSUE THREAD

**Issue by ibrahimk157** [arqma/arqma-electron-wallet#8]
Hello,

Can anyone guide me through compiling this for ARM? Specifically the raspberry pi 4B? I am a noob at this stuff so sorry if this sounds stupid.

Thanks!

**Comment by ArqTras** [comment]
I dont think all npm libraries are compatible with arm, but you may try install latest node and follow instructions. Also remmber to put in bin directory arqmad and arqma-wallet-rpc binaries available for arm on github.com/arqma/arqma
